<a href="https://colab.research.google.com/github/KUGATHAS04k/Basic-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
array  = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                   [['J','K','L'],['M','N','O'],['P','Q','R']],
                   [['S','T','U'],['V','W','X'],['Y','Z','']]])
print(array)
print(array.ndim)
print(array.shape)

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '']]]
3
(3, 3, 3)


This like layers in a cake. cool like 2 layer cake in first layer have 3 rows and 3 column

In [ ]:
word = array[1,0,1] + array[2,0,2] + array[0,2,0] + array[0,0,0]
print(word)

KUGA


##Slicing using NUMpy

In [ ]:
array2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])

In [ ]:
# array2[0:]
# array[start:end:step]
array2[2: , 0:2]

array([[ 9, 10],
       [13, 14]])

##Scaler arithmetic using *Numpy*

In [ ]:
print(array2 + 2)

print(array2 - 2)
print(array2 * 2)
print(array2 / 2)
print(array2 ** 3)
print(array2 % 2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]
 [6.5 7.  7.5 8. ]]
[[   1    8   27   64]
 [ 125  216  343  512]
 [ 729 1000 1331 1728]
 [2197 2744 3375 4096]]
[[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]]


##Vectorized Mathematical Function

In [ ]:
print(np.pi)
print(np.sqrt(array2))
print(np.round(array2))

3.141592653589793
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


###Excercise of find the Area of a circle

In [ ]:
array= np.array([1,2,3])

Area = np.pi * array ** 2
print(Area)

[ 3.14159265 12.56637061 28.27433388]


##Element wise arithmetic

In [ ]:
array3 = np.array([1,2,3])
array4 = np.array([4,5,6])

print(array3 + array4)
print(array3 - array4)
print(array3 * array4)
print(array3 / array4)
print(array3 ** array4)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


##Comparisan Operators

In [ ]:
scores = np.array([45,100,91,75,70,55])

In [ ]:
print(scores == 100)

[False  True False False False False]


In [ ]:
scores[scores < 60] = 0
print(scores)

[  0 100  91  75  70   0]


##Brodcasting using numPY


*   They are equal
*   one of them is 1.

### The Step-by-Step Process
* Align Dimensions: Align the shapes of the two arrays at the right.


* Check Compatibility: * If the dimensions are the same, you're good.

If one dimension is 1, that array is "stretched" to match the other.

If one array has fewer dimensions, prepended "1"s are added to its shape on the left until the ranks match.

* Fail Condition: If at any point the dimensions are different and neither is 1, NumPy raises a ValueError.



In [16]:
array5 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4],[1,5,9,8]])
array6 = np.array([[1],[2],[3],[4]])


print(array5.shape)
print(array6.shape)

(4, 4)
(4, 1)


In [17]:
print(array5 * array6)

[[ 1  2  3  4]
 [ 8 10 12 14]
 [21 24 27 12]
 [ 4 20 36 32]]


#Agregate Function